export const COUNTRIES = [
  { id: 1, name: 'Algeria' },
  { id: 2, name: 'Angola' },
  { id: 3, name: 'Benin' },
  { id: 4, name: 'Botswana' },
  { id: 5, name: 'Burkina Faso' },
  { id: 6, name: 'Burundi' },
  { id: 7, name: 'Cabo Verde' },
  { id: 8, name: 'Cameroon' },
  { id: 9, name: 'Central African Republic' },
  { id: 10, name: 'Chad' },
  { id: 11, name: 'Comoros' },
  { id: 12, name: 'Congo (Congo-Brazzaville)' },
  { id: 13, name: 'Côte d’Ivoire' },
  { id: 14, name: 'Djibouti' },
  { id: 15, name: 'Egypt' },
  { id: 16, name: 'Equatorial Guinea' },
  { id: 17, name: 'Eritrea' },
  { id: 18, name: 'Eswatini (fmr. "Swaziland")' },
  { id: 19, name: 'Ethiopia' },
  { id: 20, name: 'Gabon' },
  { id: 21, name: 'Gambia' },
  { id: 22, name: 'Ghana' },
  { id: 23, name: 'Guinea' },
  { id: 24, name: 'Guinea-Bissau' },
  { id: 25, name: 'Kenya' },
  { id: 26, name: 'Lesotho' },
  { id: 27, name: 'Liberia' },
  { id: 28, name: 'Libya' },
  { id: 29, name: 'Madagascar' },
  { id: 30, name: 'Malawi' },
  { id: 31, name: 'Mali' },
  { id: 32, name: 'Mauritania' },
  { id: 33, name: 'Mauritius' },
  { id: 34, name: 'Morocco' },
  { id: 35, name: 'Mozambique' },
  { id: 36, name: 'Namibia' },
  { id: 37, name: 'Niger' },
  { id: 38, name: 'Nigeria' },
  { id: 39, name: 'Rwanda' },
  { id: 40, name: 'Sao Tome and Principe' },
  { id: 41, name: 'Senegal' },
  { id: 42, name: 'Seychelles' },
  { id: 43, name: 'Sierra Leone' },
  { id: 44, name: 'Somalia' },
  { id: 45, name: 'South Africa' },
  { id: 46, name: 'South Sudan' },
  { id: 47, name: 'Sudan' },
  { id: 48, name: 'Tanzania' },
  { id: 49, name: 'Togo' },
  { id: 50, name: 'Tunisia' },
  { id: 51, name: 'Uganda' },
  { id: 52, name: 'Zambia' },
  { id: 53, name: 'Zimbabwe' },
];
